query getFile($itemId: ID = "", $appId: ID = "iea", $lang: String = "en") {
  getFile(itemId: $itemId, appId: $appId, lang: $lang) {
    createdAt
    file
    fileType
    hash
    id
    image {
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      url
    }
    name
    path
    size
    thumb
    updatedAt
    url
  }
}
