query getUser($appId: ID = "iea", $userId: ID = "") {
  getUser(appId: $appId, userId: $userId) {
    slug {
      en
      fr
    }
    admin
    branch
    createdAt
    email
    role
    status
  }
}
